### PR TITLE
fixed 'unknown function switch_buffer' error on mouse click in neovim

### PR DESCRIPTION
**Pull request by suharelli**

### CODE REVIEW

**Comment by ap** [comment]
That patch won’t work in Vim.

Also, I tested this in NeoVim. Did they change something? What version are you using?

**Comment by suharelli** [comment]
nvim version 0.4.4

**Comment by elzii** [comment]
Can confirm this works in `nvim >= 0.4.4`

**Comment by ap** [comment]
Let me know if this still doesn’t work for you. Otherwise share and enjoy 🙂

**Comment by suharelli** [comment]
Thanks, it works!

**Pull request closed without merging**
